<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Python on Note about technology</title>
    <link>https://xingelf.github.io/categories/python/</link>
    <description>Recent content in Python on Note about technology</description>
    <generator>Hugo</generator>
    <language>en</language>
    <lastBuildDate>Tue, 03 Jan 2023 00:00:00 +0000</lastBuildDate>
    <atom:link href="https://xingelf.github.io/categories/python/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Errors in Python</title>
      <link>https://xingelf.github.io/tech/python-err/</link>
      <pubDate>Tue, 03 Jan 2023 00:00:00 +0000</pubDate>
      <guid>https://xingelf.github.io/tech/python-err/</guid>
      <description>&lt;h2 id=&#34;1-invalid-comparison-between-dtypedatetime64ns-americanew_york-and-datetime64&#34;&gt;1. Invalid comparison between dtype=datetime64[ns, America/New_York] and datetime64&lt;/h2&gt;&#xA;&lt;h3 id=&#34;error&#34;&gt;Error&lt;/h3&gt;&#xA;&lt;p&gt;This error occurs when comparing timestamps in Yahoo Finance with different timezones.&lt;/p&gt;</description>
    </item>
  </channel>
</rss>
